#!/bin/bash
#https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.7/administration/authentication_and_authorization.md#set-up-authentication
mkdir -p $HOME/lib/influxdata && docker run -p 8086:8086 -e AUTH_ENABLED=true -e INFLUXDB_DB=boost_kafka_lag -e INFLUXDB_HTTP_AUTH_ENABLED=true -e INFLUXDB_ADMIN_USER=admin -e INFLUXDB_ADMIN_PASSWORD=admin -e INFLUXDB_USER=boost-kafka-lag -e INFLUXDB_USER_PASSWORD=password -v $HOME/lib/influxdata:/var/lib/influxdb influxdb:1.7.9
